version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=teste
    volumes:
      - docker_exercise_database_volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - docker_exercise_network
    
  phpmysqladmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    networks:
      - docker_exercise_network
    depends_on:
      - database
      
networks:
  docker_exercise_network:
    driver: bridge

volumes:
  docker_exercise_database_volume: